name-template: "v$RESOLVED_VERSION 🚀"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "📢 Breaking changes"
    labels:
      - "breaking change"
  - title: "✨ Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label:
      - "chore"
  - title: "Documentation"
    label:
      - "docs"
      - "documentation"
exclude-labels:
  - "skip changelog"
change-template: "- $TITLE, by @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
      - "breaking change"
  minor:
    labels:
      - "minor"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "chore"
  default: patch

autolabeler:
  - label: "enhancement"
    branch:
      - "/feature\/.+/"
  - label: "fix"
    branch:
      - "/fix\/.+/"
    title:
      - "/fix/i"
  - label: "chore"
    branch:
      - "/chore\/.+/"
  - label: "documentation"
    branch:
      - "/docs{0,1}\/.+/"

template: |
  $CHANGES
